# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_INGENIC_CGU_COMMON)	+= cgu.o pm.o
obj-$(CONFIG_INGENIC_CGU_JZ4740)	+= jz4740-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4755)	+= jz4755-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4725B)	+= jz4725b-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4760)	+= jz4760-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4770)	+= jz4770-cgu.o
obj-$(CONFIG_INGENIC_CGU_JZ4780)	+= jz4780-cgu.o
obj-$(CONFIG_INGENIC_CGU_X1000)		+= x1000-cgu.o
obj-$(CONFIG_INGENIC_CGU_X1830)		+= x1830-cgu.o
obj-$(CONFIG_INGENIC_CGU_T31)		+= t31-cgu.o
obj-$(CONFIG_COMMON_CLK_INGENIC)	+= clk.o clk-pll.o clk-div.o clk-bus.o power-gate.o
obj-$(CONFIG_CLK_T31)			+= clk-t31.o
obj-$(CONFIG_INGENIC_TCU_CLK)		+= tcu.o
